### ISSUE TITLE
How to include count(*) 

### ISSUE THREAD

**Issue by umasankarsahoo** [zbrookle/dataframe_sql#28]
Select count(*) from my_table 
This doesn't work

**Comment by umasankarsahoo** [comment]
select somecolumn,count(*) from my_table group by somecolumn

**Comment by zbrookle** [comment]
@umasankarsahoo Thanks for bringing that up,  dataframe_sql doesn't support the syntax count(*) at the moment, but in the meantime, if you do 
```sql
count(some column), somecolumn from my_table group by somecolumn
```
in theory it should give the same result

**Comment by zbrookle** [comment]
Blocked by https://github.com/zbrookle/sql_to_ibis/issues/20
