### ISSUE TITLE
Add support for delete and update statements

### ISSUE THREAD

**Issue by rugg2** [zbrookle/dataframe_sql#34]

**Comment by zbrookle** [comment]
@rugg2 Thanks for raising an issue. Could you provide more insight into what you're looking for? I'm just a bit confused because dataframe_sql isn't a database, it's just an abstraction on operations that you might perform on a pandas dataframe, like selection, aggregation, grouping, etc.

**Comment by rugg2** [comment]
My use case: I've got a bunch of SQL queries that insert and delete records from a database, but we're moving our data out of the RDS, so no more SQL queries are available. I'm interested in your library to handle those queries.

I imagine you could:
- update the original data frame: so if doing delete operation, update the data frame in place: effectively in memory database 
- alternatively you could return a new data frame: perhaps with different syntax of the type df_out = df_in.sql("delete rows query"), where df_out returns the state 
- under the hood, whether you want to keep the original dataset immutable, remove rows, or add a logical delete flag on the rows, I have no opinion

**Comment by zbrookle** [comment]
@rugg2 Ok very interesting! I'll definitely look into adding this
