### ISSUE TITLE
BUG: Not Standard/Expected SQL Syntax

### ISSUE THREAD

**Issue by NatureGeorge** [zbrookle/dataframe_sql#38]
Appreciate your work.

## Issue

I am using`dataframe_sql` to perform some simple queries. However, I found that some of the query syntaxes that `dataframe_sql` implemented were not standard enough for me.

### Input

```python
from pandas import DataFrame
from dataframe_sql import register_temp_table, query

demo_df = DataFrame({'A':[1,2,3], 'B':[4,5,6]})
register_temp_table(demo_df, "demo_df")
query("""SELECT A FROM demo_df WHERE B > 4 LIMIT 1""")
```

### Outout

```python
KeyError                                  Traceback (most recent call last)
~\Miniconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'B'
```

## Expected Output

```python
+----+
| A  | 
+----+
| 2  | 
+----+
```

### Input

```python
# NOTE: Change the Query
query("""SELECT A,B FROM demo_df WHERE B > 4 LIMIT 1""")
```

### Outout

```py
+----+----+
| A  | B  | 
+----+----+
| 2  | 5  | 
+----+----+
```

## Question

Although I can use the new query as mentioned above, I get the additional column(s) in the result and has to rewrite some of the queries in my usage for the reason that the syntax has a little bit different from the normal syntax

**Comment by zbrookle** [comment]
@NatureGeorge Great catch! Thanks for finding that, I agree it's not really the expected syntax, so I'll work on fixing that. In the meantime if you need the output you're looking for, you could use a subquery on top of 
```SQL
SELECT A,B FROM demo_df WHERE B > 4 LIMIT 1
```
such as 

```SQL
SELECT A FROM
(SELECT A,B FROM demo_df WHERE B > 4 LIMIT 1) sub
```

**Comment by zbrookle** [comment]
@NatureGeorge If you reinstall the latest version of sql_to_ibis this issue will be resolved

**Comment by NatureGeorge** [comment]
> @NatureGeorge If you reinstall the latest version of sql_to_ibis this issue will be resolved

Got it👍
