### ISSUE TITLE
error - [where variable is not null], [where variable != '']

### ISSUE THREAD

**Issue by wingsuiting** [zbrookle/dataframe_sql#41]
Hi, thank you for the great package!
Could I ask if there is any way to achieve checks for empty/null fields?

**Example:**
`"""SELECT variable FROM table WHERE variable != '' LIMIT 100"""`

**Returns:**
```
Invalid query!
Expected one of the following input(s): {'__ANON_5'}
Unexpected input at line 3, column 56
lding_building_name_building_number != ''
```

**Comment by zbrookle** [comment]
@wingsuiting Thanks! I appreciate you using my package! That's actually a good catch, I didn't have a test for that, but it should work. I'll let you know when that's patched

**Comment by wingsuiting** [comment]
Thank you! I did spot one more bug (feature?) where subqueries also
experience syntax errors:

SELECT variable_1, variable_2 FROM table_1 WHERE variable_2 IN (SELECT
variable_3 FROM table_2)

**Comment by zbrookle** [comment]
@wingsuiting Awesome! If you could actually make a separate issue for that, it would be really helpful

**Comment by wingsuiting** [comment]
Of course, that's done!
