### ISSUE TITLE
subqueries experience syntax errors

### ISSUE THREAD

**Issue by wingsuiting** [zbrookle/dataframe_sql#42]
Subqueries using an IN or NOT IN statement are presently failing. Example:

SELECT variable_1, variable_2 FROM table_1 WHERE variable_2 IN (SELECT
variable_3 FROM table_2)

**Comment by zbrookle** [comment]
@wingsuiting I just looked and actually have a unit test for this already. The way that I implemented subqueries, they need to have an alias at the moment, so let me know if that works. For example it would be 

```SQL
SELECT variable_1, variable_2 FROM table_1 WHERE variable_2 IN (SELECT
variable_3 FROM table_2) t1
```

I'm definitely open to changing it so that it isn't necessary to have an alias though
