### ISSUE TITLE
How to query a data frame with spaces in the column names and/or numbers as column names

### ISSUE THREAD

**Issue by sreeanthrds** [zbrookle/dataframe_sql#45]
Hi,

   I love this package to write sql queries on pandas data frames. But, I have few data sets. They usually have spaces in the column names. Also in some cases only just numbers as the columns such as year. Could you please help me, how to address this issue. Also, kindly help with some documentation if you have any.

**Comment by zbrookle** [comment]
@sreeanthrds Thanks for pointing that out, it's actually something I've been meaning to add to this package. Once it's added the column names will need double quotes (") around the name. I'll update this issue once that feature is added

**Comment by zbrookle** [comment]
@sreeanthrds In terms of documentation, you can find the full sql syntax [here](https://github.com/zbrookle/sql_to_ibis)
