### ISSUE TITLE
Issue in join queries

### ISSUE THREAD

**Issue by itsds** [zbrookle/dataframe_sql#47]
Hello,

I tried to execute the below three queries using dataframe_sql. but only first and third are working, ideally, all three should work as there in proper SQL format. Its saying error as - "Joined tables have overlapping names: ['pid', 'pdh', 'enddate', 'dep_head', 'serialNo']".

1. SELECT table1.pdh as pdh
FROM table1 as t1
inner join table2 as t2 on (t2.serialNo=t1.serialNo and t2.pdh=t1.pdh)

2. SELECT table1.pdh as pdh
FROM table1 as t1
inner join table2 as t2 on (t2.serialNo=t1.serialNo and t2.pdh=t1.pdh)
where s2 < '100'

3. SELECT *
FROM table1 as t1
inner join table2 as t2 on (t2.serialNo=t1.serialNo and t2.pdh=t1.pdh)
where s2 < '100'

**Comment by zbrookle** [comment]
@itsds Thanks for bring this up, I'll look into it!
