### ISSUE TITLE
How to use Count(distinct ID)

### ISSUE THREAD

**Issue by MinhAnhL** [zbrookle/dataframe_sql#51]
Dear zbrookle, 
thank you for this useful package.

I'm currently trying to find duplicates and want to apply a distinct count.
However, count(distinct ID_Nr) seems not to work.

`query("""SELECT COUNT(DISTINCT ID_NR) FROM data""")`

Do you have any suggestions on how I can do this with your package?

Thank you, 
Best,
Minh

**Comment by zbrookle** [comment]
@MinhAnhL Thanks for pointing that out, I don't think I have support for that yet, but I can add it
