### ISSUE TITLE
module 'sqlalchemy' has no attribute 'Binary'

### ISSUE THREAD

**Issue by jlsevillano** [zbrookle/dataframe_sql#57]
I'm try to do a simple query.
I load my DataFrame (Pandas) 600.000 rows - OK
After:
q = '''SELECT id_data FROM pd LIMIT 10;'''
dataframe_sql.register_temp_table(pdDataFrame, "my_table")
dataframe_sql.query(q)

And fails:
AttributeError: module 'sqlalchemy' has no attribute 'Binary'

I'm not sure but I found that:
https://stackoverflow.com/questions/65851741/attributeerror-module-sqlalchemy-has-no-attribute-binary

Am I making some mistake or the issue is my sqlalchemy version?

Package           Version
----------------- --------
astroid           2.4.2   
colorama          0.4.4   
dataframe-sql     0.4.0   
greenlet          1.1.0   
ibis-framework    1.4.0   
isort             5.7.0   
lark-parser       0.8.5   
lazy-object-proxy 1.4.3   
mccabe            0.6.1   
multipledispatch  0.6.0   
numpy             1.20.1
pandas            1.2.3
pandasql          0.7.3
pip               21.1.3
psycopg2          2.8.6
pylint            2.6.0
pyModbusTCP       0.1.8
pyserial          3.5
python-dateutil   2.8.1
pytz              2021.1
regex             2021.7.6
setuptools        49.2.1
six               1.15.0
sql-to-ibis       0.4.0
SQLAlchemy        1.4.21
tabulate          0.8.7
toml              0.10.2
toolz             0.11.1
uModbus           1.0.4
urllib3           1.26.3
wrapt             1.12.1

**Comment by zbrookle** [comment]
So it looks like you have a few extra characters in your query, you can remove the ' from either side since you already have a string. Also you shouldn't need the ; at the end. Let me know if that helps

**Comment by jlsevillano** [comment]
Some error:
AttributeError: module 'sqlalchemy' has no attribute 'Binary'
Code:
data = extract_data.loadDataSource(6100000,6172553)
    
pdDataFrame = pd.DataFrame(data = data,
                        columns=['id_data',])
    
dataframe_sql.register_temp_table(pdDataFrame, "my_table")
dataframe_sql.query('SELECT id_data FROM pd LIMIT 10')

**Comment by jlsevillano** [comment]
Same Error:
AttributeError: module 'sqlalchemy' has no attribute 'Binary'

Code:
data = extract_data.loadDataSource(6100000,6172553)
    
    pdDataFrame = pd.DataFrame(data = data,
                        columns=['id_data',])
    
    dataframe_sql.register_temp_table(pdDataFrame, "my_table")
    dataframe_sql.query('SELECT id_data FROM my_table LIMIT 10')

**Comment by zbrookle** [comment]
Can you paste the full stack trace?

**Comment by jlsevillano** [comment]
![imagen](https://user-images.githubusercontent.com/12149268/125981737-d519ef7b-3638-4d72-8394-6202de54ee23.png)
import pandas as pd
import pandasql as ps

import dataframe_sql

import multiprocessing as mp
from sys import exit
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning) 

from datetime import datetime

import config
import process

from utils import extract_data

def main():
    
    print('\n################ INIT MAIN PROCESS ####################')
    
    print("Number of processors: ", mp.cpu_count())
    config.nodo = 'CTB-001'

    d1 = datetime(2020, 1, 1, 8, 0, 0) 
    d2 = datetime(2020, 1, 1, 10, 0, 0) 

    print(datetime.now().strftime('%Y-%m-%d %H:%M:%S'))


    data = extract_data.loadDataSource(6100000,6172553) #Loading from Postgres DB
    
    pdDataFrame = pd.DataFrame(data = data,
                        columns=['id_data',])
    
    dataframe_sql.register_temp_table(pdDataFrame, "my_table")
    dataframe_sql.query('SELECT id_data FROM my_table LIMIT 10')
    
if __name__ == '__main__':

    main()

**Comment by zbrookle** [comment]
Since, you're not using pandasql, I would take this line out "import pandasql as ps". I would also make sure that in your python environment you uninstall any packages you don't actually need, particularly pandasql. On init it seems that ibis looks through the current backends available, and it's finding sqlite, which you may not have configured properly for ibis (which is fine because you're not using it anyway). If you need extra help, I would suggest going and asking the ibis team, since this issue seems to be occurring in their package
